### ISSUE TITLE
Tested under Matterhorn 2.0?

### ISSUE THREAD

**Issue by djcp** [polimediaupv/paella-matterhorn#14]
Have we tested the paella player in matterhorn 2.0, which is slated for a summer release? Thanks!

**Comment by miesgre** [comment]
We didn't test paella under matterhorn 2.0. We need to do it.
But, I think it should work.

We don't have any matterhorn 2.0 server at this moment. If you have. maybe you can try to compile it. You only need to modify the pom.xml for 1.6 and change the matterhorn version to try if it works.

**Comment by miesgre** [comment]
I tested paella-matterhorn in opencast 2.0.0-beta2 and it works ok.
