### ISSUE TITLE
Why is the SERIES endpoint necessary?

### ISSUE THREAD

**Issue by spiraleddy** [polimediaupv/paella-matterhorn#16]
The player uses the SEARCH endpoint to find recordings and will not get results for recordings that it does have access to. Is the Series ACL only really valuable for detecting WRITE access for when recording editing is enabled in the player?

**Comment by miesgre** [comment]
Karen, 

Paella uses the series endpoint to read the acl
https://github.com/polimediaupv/paella-matterhorn/blob/master/paella-matterhorn/javascript/05_initdelegate.js#L27-L35

Then paella uses the ACL to check if the user has READ/WRITE permissions
https://github.com/polimediaupv/paella-matterhorn/blob/master/paella-matterhorn/javascript/02_accesscontrol.js#L35-L47

If you don't want to use the editor, I think that the series acl call is not necessary.
Maybe we can check if the editor es enabled/disabled in config.json file and make the call to the series or not

**Comment by spiraleddy** [comment]
That would be great to be able to avoid the Series ACL call when the editor is disabled. 

I also notice that  Search endpoint /search/series.json?id=xyz returns a rich set of series meta-data comparable to the data retrieved by the Series endpoint /series/xyz.json.

The purpose for avoiding the Series REST endpoint is because the series-impl loads on the OC Admin server by default OC distributed installs. The series-remote, and search-impl loads on the OC Engage server. When the OC Admin server is down or is under heavy load, our Paella player is unable to play videos, even though the OC Engage server is up, because the OC Engage server's series-remote cannot talk to the series-impl and cannot respond to the player's Series endpoint calls. 

The two options for protecting the player when the OC admin is under stress is to move the Series index off the admin or allow the Player to avoid the Series endpoint.

**Comment by miesgre** [comment]
With the changes in paella player 5.0 with the access system, now there is no need to call the /series endpoints for viewing the videos. You can take a look to the [`release/5.0.0`](/polimediaupv/paella-matterhorn/tree/release/5.0.0) branch.
