### ISSUE TITLE
It cannot play videos ingested from Galicaster 2.0 beta

### ISSUE THREAD

**Issue by fishfree** [polimediaupv/paella-matterhorn#18]
The webpage always shows progress circle icon.

**Comment by miesgre** [comment]
Do you encode your videos in h264/aac? Are those videos playable in Theodul?

Can you post a Link to a video that fails, so I can check?

**Comment by fishfree** [comment]
It's my fault. I forgot changing the Galicaster workflow from "full" to "ng-schedule-and-upload" after upgrading my Opencast to 2.2.
