### ISSUE TITLE
Paella-matterhorn's usertracking "type" field overflow causes 500 error in OC endpoint

### ISSUE THREAD

**Issue by spiraleddy** [polimediaupv/paella-matterhorn#19]
The Opencast user tracking's database "type" field is only 128 chars ( VARCHAR(128) [1]), but the "type" value is often longer than that when coming from the userTrackerSaverPlugin for unknown events (default switch on the "type" value construction) [2] [3]. When the type is too long, Opencast sends back a "NetworkError: 500 Internal Server Error" and the even is not tracked on Opencast side. 

[1] https://bitbucket.org/opencast-community/matterhorn/src/6184be4c2b4a59da66b63e586ffd233bef46b3ba/docs/scripts/ddl/mysql5.sql?at=r%2F2.2.x&fileviewer=file-view-default#mysql5.sql-279

[2] Example of a common "paella:VideoContainer:setupVideo" event's type value (242 chars):
_paella:VideoContainer:setupVideo:slave;{"src":"http://my.university.edu/engage-player/1734cbf2-040b-4291-af45-fcc2f7a883a2/65066c22-7b01-4de0-aa4c-8cffeac77cf6/myVideo.mp4","type":"video/mp4","res":{"w":"1440","h":"810"},"isLiveStream":false}_

[3] https://github.com/polimediaupv/paella-matterhorn/blob/5.0.11/paella-opencast/plugins/es.upv.paella.opencast.userTrackingSaverPlugIn/mh_usertracking_saver.js#L55

**Comment by miesgre** [comment]
Hi Karen,
Thanks for the report. 

Here, I see two solutions:

1. Do not log unknown events
2. Log only the event name, but nut the event parameters

Whitch do you think is the best solution?

**Comment by spiraleddy** [comment]
Hi Miguel, 

I like solution #2 is better. It preserves a record of tracked, but unknown, events inside a short message. 

A more complicated solution, but potentially useful for non-Opencast adopters, is to add a max size param to this plugin's config. Opencast adopters would keep the max size to 128, but others could keep the size large to accept large param'd events. 

However, I'm happy with solution #2. 

Thank you,
Karen

**Comment by spiraleddy** [comment]
I'm also Ok with #1, since it keeps the tracking concise to just the important events, and filters out all the others. However, I personally like too much data over too little, so I prefer #2 over #1.
