### ISSUE TITLE
Installation details

### ISSUE THREAD

**Issue by maxtrix** [polimediaupv/paella-matterhorn#27]
I installed Paella in opencast 2.3 and works very well, but the installation documentation need some tweaks.

1. In the point number 4 "Copy the paella bundle to your Opencast installation" you need to specify that the .jar called `paella-engage-ui-{Version}.jar` generated by the maven build is the file you need to move to the opencast installation. Also, the default place that maven put this jar is in: 
`/$home/.m2/repository/org/opencastproject/paella/paella-engage-ui/` This was discussed in the opencast groups.

2. Add the comment that the `$OPENCAST_HOME` default place is `/usr/share/opencast`.

This tweaks will be more easy to understand how to install paella in opencast

**Comment by mostolog** [comment]
Hi.

We have built 3.0 from git repo, but seems isn't clear enough if we have to set <opencast.version> to

> 3.0-SNAPSHOT

or

> 3.0

Regards

**Comment by miesgre** [comment]
I didn't test paella with opencast 3.0 and I don't know if it works, 
but in `<opencast.version>` you need to put the same version that opencast.

At this moment, in `r/3.0.x`, opencast version is `<version>3.0-SNAPSHOT</version>` 

https://bitbucket.org/opencast-community/matterhorn/src/6c40e1c5129233b55172ae973573e0ba6aaf8b39/pom.xml?at=r%2F3.x&fileviewer=file-view-default#pom.xml-8

**Comment by mostolog** [comment]
Hi Miguel

Downloaded source, followed build instructions and still getting a 404:
http://redacted:8080/paella/ui/watch.html?id=7aea040b-2ed4-4b14-9e7e-afb443837107

Any ideas?

**Comment by miesgre** [comment]
What version of opencast are you using?

**Comment by mostolog** [comment]
3.0-SNAPSHOT

**Comment by miesgre** [comment]
@mostolog Did you add the lines:
```
<sec:intercept-url pattern="/paella/ui/auth.html" access="ROLE_USER" />
<sec:intercept-url pattern="/paella/ui/**" access="ROLE_ANONYMOUS" />
```
to the ${$OPENCAST_HOME}/etc/security/mh_default_org.xml file?

Before or After the `<sec:intercept-url pattern="/**" access="ROLE_ADMIN, ROLE_COURSE_ADMIN" />`?
You need to put the lines before the `/**` pattern

**Comment by mostolog** [comment]
Long before. I just noticed it's not on a new line...but that shouldn't cause any problem, isnt it?
```
<!-- ################ -->
    <!-- # URL SECURITY # -->
    <!-- ################ -->

    <!-- Allow anonymous access to the login form --><sec:intercept-url pattern="/paella/ui/auth.html" access="ROLE_USER" /><sec:intercept-url pattern="/paella/ui/**" access="ROLE_ANONYMOUS" />
    <sec:intercept-url pattern="/admin-ng/login.html" access="ROLE_ANONYMOUS" />
   ...
```

**Comment by mostolog** [comment]
No, I can't

**Comment by mostolog** [comment]
Any ideas?

**Comment by miesgre** [comment]
@mostolog It seems that paella bundle is not installed or loaded.
Are you sure paella bundle is installed?

BTW, Is better to move this thread to the paella mailing list. Please rewrite your question there.
